### ISSUE TITLE
Smart contract doesn't support object array

### ISSUE THREAD

**Issue by Qiao-Jin** [neo-project/neo-vm#242]
It seems that neo-compiler & neo-vm doesn't support object array in smart contract currently, i.e.

```
using Neo.SmartContract.Framework;
using System.Numerics;

namespace TestArray
{
    public class Contract1 : SmartContract
    {
        public static object Main(string operation, object[] args)
        {
            State[] states = new State[] { new State() };
            for (var i = 0; i < 1; i++)
            {
                State state = states[i];
            }
            return true;
        }

        public struct State
        {
            public byte[] from;
            public byte[] to;
            public BigInteger amount;
        }
    }
}
```

The simple smart contract will report an error if built in release mode: 

```
IL_000D Ldelema  ---> System.Exception: unsupported instruction Ldelema
```	

After researching I found out this is due to some lack of function in func `neo-compiler\neon\MSIL\Converter.ConvertCode`:

```
case CodeEx.Switch:
{
    throw new Exception("need neo.VM update.");
    //var addrdata = new byte[src.tokenAddr_Switch.Length * 2 + 2];
    //var shortaddrcount = (UInt16)src.tokenAddr_Switch.Length;
    //var data = BitConverter.GetBytes(shortaddrcount);
    //addrdata[0] = data[0];
    //addrdata[1] = data[1];
    //var code = _Convert1by1(VM.OpCode.SWITCH, src, to, addrdata);
    //code.needfix = true;
    //code.srcaddrswitch = new int[shortaddrcount];
    //for (var i = 0; i < shortaddrcount; i++)
    //{
    //    code.srcaddrswitch[i] = src.tokenAddr_Switch[i];
    //}
    }
    break;
```	

This piece of code is commented out because VM.OpCode.SWITCH and corresponding logic is not yet defined. By blaming the code it seems this piece of code is inserted in 2017. I suppose this pending functionality might be forgotten?

Furthermore, even if it can be built successfully under debug mode, still an error would occur if run on chain. After debugging it seems that there is an array bound problem in func `neo-vm\src\neo-vm\ExecutionEngine.ExecuteInstruction`, case OpCode.PICKITEM.

Could anyone have a look at this problem?

**Comment by Tommo-L** [comment]
@lightszero da lao, Could we support this `CodeEx.Switch`. We are blocked by this 😂

**Comment by lightszero** [comment]
> @lightszero da lao, Could we support this `CodeEx.Switch`. We are blocked by this 😂

I don't think this is about switch.

it is looks like is a bug of array.

**Comment by Qiao-Jin** [comment]
> > @lightszero da lao, Could we support this `CodeEx.Switch`. We are blocked by this 😂
> 
> I don't think this is about switch.
> 
> it is looks like is a bug of array.
> 
> and use neo-devpack-dotnet ,neo-compiler had be closed.

Could you provide more detailed information? I suppose neo-devpack-dotnet and neo-compiler are used in different occasions.

**Comment by lightszero** [comment]
neo-compiler just had be closed long long ago,so never use it anymore.

**Comment by Qiao-Jin** [comment]
> neo-compiler had be closed long long ago,so never use it anymore.

Besides neo-compiler, is there any other compilers that can be used for neo smart contract? Can neo-devpack-dotnet be used an alternative compiler? Thx

**Comment by lightszero** [comment]
neo-devpack-dotnet contains smart contract compiler

**Comment by Qiao-Jin** [comment]
> neo-devpack-dotnet contains smart contract compiler

Is thare any doc on how to use neo-devpack-dotnet as compiler? Thx

**Comment by Qiao-Jin** [comment]
> neo-devpack-dotnet contains smart contract compiler

I tried with neo-devpack-dotnet to compile the example contract but still failed.

Exactly the same problem happens for release mode: IL_000D Ldelema  ---> System.Exception: unsupported instruction Ldelema, and below is corresponding stacktrace:

```
at Neo.Compiler.MSIL.ModuleConverter.ConvertCode(ILMethod method, OpCode src, NeoMethod to) in C:\Repos\neo-devpack-dotnet\Neo.Compiler.MSIL\MSIL\Converter.cs:line 552
at Neo.Compiler.MSIL.ModuleConverter.ConvertMethod(ILMethod from, NeoMethod to) in C:\Repos\neo-devpack-dotnet\Neo.Compiler.MSIL\MSIL\Converter.cs:line 333
   --- End of inner exception stack trace ---
at Neo.Compiler.MSIL.ModuleConverter.ConvertMethod(ILMethod from, NeoMethod to) in C:\Repos\neo-devpack-dotnet\Neo.Compiler.MSIL\MSIL\Converter.cs:line 337
at Neo.Compiler.MSIL.ModuleConverter.Convert(ILModule _in, ConvOption option) in C:\Repos\neo-devpack-dotnet\Neo.Compiler.MSIL\MSIL\Converter.cs:line 133
at Neo.Compiler.Program.Main(String[] args) in C:\Repos\neo-devpack-dotnet\Neo.Compiler.MSIL\Program.cs:line 108
```

Exception also occurs for debug mode:

```
IL_000D Ldelema  ---> System.Exception: unsupported instruction Ldelema
   in: System.Object TestArray.Contract1::Main(System.String,System.Object[])

   at Neo.Compiler.MSIL.ModuleConverter.ConvertCode(ILMethod method, OpCode src, NeoMethod to) in C:\Repos\neo-devpack-dotnet\Neo.Compiler.MSIL\MSIL\Converter.cs:line 1030
   at Neo.Compiler.MSIL.ModuleConverter.ConvertMethod(ILMethod from, NeoMethod to) in C:\Repos\neo-devpack-dotnet\Neo.Compiler.MSIL\MSIL\Converter.cs:line 333
   --- End of inner exception stack trace ---
   at Neo.Compiler.MSIL.ModuleConverter.ConvertMethod(ILMethod from, NeoMethod to) in C:\Repos\neo-devpack-dotnet\Neo.Compiler.MSIL\MSIL\Converter.cs:line 337
   at Neo.Compiler.MSIL.ModuleConverter.Convert(ILModule _in, ConvOption option) in C:\Repos\neo-devpack-dotnet\Neo.Compiler.MSIL\MSIL\Converter.cs:line 175
   at Neo.Compiler.Program.Main(String[] args) in C:\Repos\neo-devpack-dotnet\Neo.Compiler.MSIL\Program.cs:line 113
```

**Comment by lightszero** [comment]
ok,I will checking this bug.

**Comment by Qiao-Jin** [comment]
> ok,I will checking this bug.

After re-checking still the array bounds problem exists for neo-devpack-dotnet in case of object array.

**Comment by Qiao-Jin** [comment]
> ok,I will checking this bug.

Hi! Is there news upon this problem? Thx!

**Comment by lightszero** [comment]
public static object TestStructArrayInit()
        {
            var s = new State();
            State[] states = new State[] {s};
            for (var i = 0; i < 1; i++)
            {
                State state = states[i];
                return state;
            }
            return null;
        }

this is working.

problem is  new State[] {s}; only support simple expr fornow.

if use new State[] {new State()}
will got a [null] array.

this is bug,but you can skip it fornow.

**Comment by Tommo-L** [comment]
Hi @shargon, could you help us move this issue to `neo-devpack-dotnet`

@lightszero we have cofirmed, in debug mode, it works well. But in release mode, it does have a compile error.  Currently we are not very familiar with the compiler and need your help.

```C#
using Neo.SmartContract.Framework;
using System.Numerics;

namespace TestArray
{
    public class Contract1 : SmartContract
    {
        public static object Main(string operation, object[] args)
        {
            State s = new State();
            State[] states = new State[] { s };
            for (var i = 0; i < 1; i++)
            {
                State state = states[i];
            }
            return true;
        }

        public struct State
        {
            public byte[] from;
            public byte[] to;
            public BigInteger amount;
        }
    }
}
```
Debug mode:
![image](https://user-images.githubusercontent.com/43396869/70695352-79432000-1cfc-11ea-9fdd-b935ae1442ad.png)


Release mode:
![image](https://user-images.githubusercontent.com/43396869/70695384-8e1fb380-1cfc-11ea-9531-2178e7f3e18d.png)

**Comment by Tommo-L** [comment]
Another problem is the following case in release mode,  however, it works well in debug mode still.

![image](https://user-images.githubusercontent.com/43396869/70696345-79441f80-1cfe-11ea-97e8-0872a3881714.png)

vs

![image](https://user-images.githubusercontent.com/43396869/70696473-bdcfbb00-1cfe-11ea-9ec3-6de576a1f4cd.png)
