### ISSUE TITLE
Suspicion something non-deterministic is happening in the current VM

### ISSUE THREAD

**Issue by jsolman** [neo-project/neo-vm#53]
When syncing from the MainNet chain file (as obtained from http://sync.ngd.network/) on multiple occasions, I randomly get exceptions to occur when deducting NEO balances (see https://github.com/neo-project/neo/issues/391).

I thought it was gone after moving to the latest VM since I was able to sync **once** without an issue after moving to latest [commit 94a91ae6 ](https://github.com/neo-project/neo-vm/commit/94a91ae63b95ee49c58c6d7468fa766637999c07). I was originally on [commit ab74c361](https://github.com/neo-project/neo-vm/commit/ab74c36117ef1afa5ccf80e326655598fd4012d5). However, upon syncing the chain again, it happened again. 

I added a richer log to see a bit more information about what was happeining. Here is an example of what I got on two separate occasions syncing the chain:

```
2018-09-25 19:14:41.118 F  Neo.Ledger.Blockchain: Account (ANcEb4Xw8ouJnk5e5Q1z6o92Z67pNrydQ2 = 0x1e9ca763049717f04952a1c0118678098a33f64a) doesn't have a balance for asset 0xc56f33fc6ecfcd0c225c4ab356fee59390af8560be0e930faebe74a6daff7c9b 1 Block: 1858860
System.Collections.Generic.KeyNotFoundException: The given key '0xc56f33fc6ecfcd0c225c4ab356fee59390af8560be0e930faebe74a6daff7c9b' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Neo.Ledger.Blockchain.Persist(Block block) in [redacted]/neo/Ledger/Blockchain.cs:line 532
...
...
```
```
2018-09-26 02:41:58.910 F  Neo.Ledger.Blockchain: Account (AWnA7E3tNpc3vtYRWdxkHYiRBBu2mSsAYR = 0xf23af39524ce9e711eaac979a015e384a7a097a4) doesn't have a balance for asset 0xc56f33fc6ecfcd0c225c4ab356fee59390af8560be0e930faebe74a6daff7c9b 1 Block: 2582510
System.Collections.Generic.KeyNotFoundException: The given key '0xc56f33fc6ecfcd0c225c4ab356fee59390af8560be0e930faebe74a6daff7c9b' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Neo.Ledger.Blockchain.Persist(Block block) in /home/solinsky/repos/aph-server/neo/Ledger/Blockchain.cs:line 532
[ERROR][9/26/18 2:41:58 AM][Thread 0010][akka://NeoSystem/user/$a] The given key '0xc56f33fc6ecfcd0c225c4ab356fee59390af8560be0e930faebe74a6daff7c9b' was not present in the dictionary.
Cause: System.Collections.Generic.KeyNotFoundException: The given key '0xc56f33fc6ecfcd0c225c4ab356fee59390af8560be0e930faebe74a6daff7c9b' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Neo.Ledger.Blockchain.Persist(Block block) in [redacted]/neo/Ledger/Blockchain.cs:line 532
   at Neo.Ledger.Blockchain.OnImport(IEnumerable`1 blocks) in [redacted]/neo/Ledger/Blockchain.cs:line 250
   at Neo.Ledger.Blockchain.OnReceive(Object message) in [redacted]/neo/Ledger/Blockchain.cs:line 413
```
 **My best theory so far is that something happening during execution of a script was non-deterministic leaving the balance of an account in a state different from what it was at the time the consensus node forged the block using a previous version of the VM. This is a theory that needs to be confirmed.** It has happened on different hardware now, so I don't think it is faulty hardware, and I'm using the same version of LevelDB I have been using for a while before having encountered this.
This is running Neo 2.9.0, maybe I should try against 2.8.0 to see if it ever happens with latest VM to see if my assumption that it is VM related is correct.

Anyway, the only difference to my PersistBlock function that threw the above exceptions is the exception handling. I added comments to the PersistBlock function also to aid in thinking through what might be happening. I'll include the top part of the function that I modified to give more info here in case someone else has more time to look into it.

This code starts on line 439 of Blockchain.cs:
```
        private void Persist(Block block)
        {
            using (Snapshot snapshot = GetSnapshot())
            {
                snapshot.PersistingBlock = block;
                snapshot.Blocks.Add(block.Hash, new BlockState
                {
                    SystemFeeAmount = snapshot.GetSysFeeAmount(block.PrevHash) + (long)block.Transactions.Sum(p => p.SystemFee),
                    TrimmedBlock = block.Trim()
                });
                foreach (Transaction tx in block.Transactions)
                {
                    snapshot.Transactions.Add(tx.Hash, new TransactionState
                    {
                        BlockIndex = block.Index,
                        Transaction = tx
                    });
                    snapshot.UnspentCoins.Add(tx.Hash, new UnspentCoinState
                    {
                        Items = Enumerable.Repeat(CoinState.Confirmed, tx.Outputs.Length).ToArray()
                    });
                    foreach (TransactionOutput output in tx.Outputs)
                    {
                        AccountState account = snapshot.Accounts.GetAndChange(output.ScriptHash, () => new AccountState(output.ScriptHash));
                        if (account.Balances.ContainsKey(output.AssetId))
                            account.Balances[output.AssetId] += output.Value;
                        else
                            account.Balances[output.AssetId] = output.Value;
                        if (output.AssetId.Equals(GoverningToken.Hash) && account.Votes.Length > 0)
                        {
                            foreach (ECPoint pubkey in account.Votes)
                                snapshot.Validators.GetAndChange(pubkey, () => new ValidatorState(pubkey)).Votes += output.Value;
                            snapshot.ValidatorsCount.GetAndChange().Votes[account.Votes.Length - 1] += output.Value;
                        }
                    }
                    
                    // Iterate all tx inputs grouped together by common input transactions.
                    foreach (var group in tx.Inputs.GroupBy(p => p.PrevHash))
                    {
                        // Get the transaction state in common for the group of transactions to process.
                        TransactionState tx_prev = snapshot.Transactions[group.Key];
                        
                        // For each input from this transaction.
                        foreach (CoinReference input in group)
                        {
                            // Mark the UTXO for the input as spent
                            snapshot.UnspentCoins.GetAndChange(input.PrevHash).Items[input.PrevIndex] |= CoinState.Spent;
                            TransactionOutput out_prev;
                            try
                            {
                                // Get the output from the the previous transaction that is now being spent.
                                out_prev = tx_prev.Transaction.Outputs[input.PrevIndex];
                            }
                            catch (Exception ex)
                            {
                                logger.Fatal($"Can't find the output being spent from tx hash: {input.PrevHash} index: {input.PrevIndex}{Environment.NewLine}{ex}");
                                // This really should never happen or something is bad wrong!
                                throw;
                            }

                            // Get the account for the address that owned the output being spent.   
                            AccountState account = snapshot.Accounts.GetAndChange(out_prev.ScriptHash);
                            
                            // If governing token was spent
                            if (out_prev.AssetId.Equals(GoverningToken.Hash))
                            {
                                // Keep track when this transaction input was spent to be able to calculate claims.
                                snapshot.SpentCoins.GetAndChange(input.PrevHash, () => new SpentCoinState
                                {
                                    TransactionHash = input.PrevHash,
                                    TransactionHeight = tx_prev.BlockIndex,
                                    Items = new Dictionary<ushort, uint>()
                                }).Items.Add(input.PrevIndex, block.Index);
                                
                                if (account.Votes.Length > 0)
                                {
                                    // Reduce number of votes selected validators have due to the voter's reduced
                                    // governing token blance.
                                    foreach (ECPoint pubkey in account.Votes)
                                    {
                                        ValidatorState validator = snapshot.Validators.GetAndChange(pubkey);
                                        validator.Votes -= out_prev.Value;
                                        if (!validator.Registered && validator.Votes.Equals(Fixed8.Zero))
                                            snapshot.Validators.Delete(pubkey);
                                    }
                                    snapshot.ValidatorsCount.GetAndChange().Votes[account.Votes.Length - 1] -= out_prev.Value;
                                }
                            }

                            try
                            {
                                // Reduce the balance of the asset by the account that owned the asset being spent
                                // by the the number of units of the asset that were spent. 
                                account.Balances[out_prev.AssetId] -= out_prev.Value;
                            }
                            catch (Exception ex)
                            {
                                logger.Fatal($"Account ({account.ScriptHash.ToAddress()} = {account.ScriptHash}) doesn't have a balance for asset {out_prev.AssetId} {out_prev.Value} Block: {block.Index}{Environment.NewLine}{ex}" );
                                // This really should never happen or something is bad wrong!
                                throw;
                            }
                        }
                    }
...
```

**Comment by jsolman** [comment]
Maybe by examining common script calls made by `ANcEb4Xw8ouJnk5e5Q1z6o92Z67pNrydQ2` and by `AWnA7E3tNpc3vtYRWdxkHYiRBBu2mSsAYR` it will give a clue as to what operations might have been non-deterministic. I wish I had more information already to go on, but I had a lot of other things going on and not able to give this issue a lot of time yet.

If anyone else has reproduced and is looking into it, comment here and let me know.

**Comment by igormcoelho** [comment]
@jsolman that's a very good initiative! Vitor and I have been discussion with Wingy and others regarding how to provide a more stable platform regarding storage. I'll take a look soon on this issue... you can use ` ` `cs on github to put C# code (with highlighting and stuff) ;)

**Comment by erikzhang** [comment]
I can't reproduce this issue. None of the nodes I ran encountered this problem. Includes all consensus nodes and seed nodes in both mainnet and testnet.

**Comment by jsolman** [comment]
what version of leveldb are they running? Maybe something is wrong with my leveldb. I’ll look into that first.

**Comment by apheliontoken** [comment]
MainNet Consesnus nodes are not running the latest VM. I have confirmed it even though no one seems to say what vm code they are actually running.

**Comment by jsolman** [comment]
MainNet Consesnus nodes are not running the latest VM. I have confirmed it even though no one seems to say what vm code they are actually running.

**Comment by jsolman** [comment]
Maybe for Neo 3.0 the gas consumed for a block during the contract execution can be included in the block header and any changes to vm can be explicitly enabled by block height.

This would be less expensive to calculate and way less resource intensive than the merkle tree of storage, etc, but merkle tree of storage allows light nodes to verify their storage retrieved using block headers; maybe want both.

**Comment by erikzhang** [comment]
The consensus nodes will be upgraded to 2.9 next week as planned.

**Comment by jsolman** [comment]
Latest chain files with current neo core master code base are now syncing without issue.

**Comment by jsolman** [comment]
BTW in case anyone else hits this, I am fairly sure the issue was actually breaching the maximum open files limit for the process. Make sure to up those when syncing from chain file if using a very fast disk and running on a flavor of Linux with a default file descriptor limit of 1024.
